name: Build Linux x64
run-name: Building SiYuan note for my Linux x64 server
on: [push]
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: "Check Debian version:"
        run: cat /etc/debian_version
      - uses: actions/checkout@v4
      - name: check PWD
        run: echo $PWD && export WORKDIR=$PWD
      - name: List files in the repository
        run: ls 
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: build app
        run: cd app && npm install -g pnpm@8.14.1 && pnpm install && pnpm run build
      - run: ls -R
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'
      - name: setup go env
        run: export GO111MODULE=on && export CGO_ENABLED=1
      - name: build kernel
        run: cd ../kernel && go build --tags fts5 -v -ldflags "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
      - run: ls -R
      - run: echo "ğŸ This job's status is ${{ job.status }}."
